/*
AlarmID: Her alarm için benzersiz kimlik
MusteriID: İlgili müşteri kimliği
AlarmTipi: Alarm türü (örn. YÜKSEK RİSK, GECİKMELİ ÖDEME)
AlarmTarihi: Alarm oluşturulma tarihi
Aciklama: Alarm açıklaması / nedeni
Durum: Alarm durumu (AKTIF, KAPANDI)
*/

CREATE TABLE Alarm (
    AlarmID     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MusteriID   NUMBER       NOT NULL,                                   
    AlarmTipi   VARCHAR2(50),                                      
    AlarmTarihi DATE         DEFAULT SYSDATE,                            
    Aciklama    VARCHAR2(200),                                      
    Durum       VARCHAR2(20) DEFAULT 'AKTIF'                           
);

/*
RiskSkoruKontrolEt: Müşteri risk skorunu kontrol eder ve eşik aşımı durumunda alarm üretir
AlarmEkle: Yeni alarm kaydı oluşturur
AlarmKapat: Mevcut alarmı kapatır (Durum = 'KAPANDI')
*/

CREATE OR REPLACE PACKAGE Alarm_Pkg IS

    PROCEDURE RiskSkoruKontrolEt(
        p_MusteriID NUMBER
    );

    PROCEDURE AlarmEkle(
        p_MusteriID NUMBER,
        p_AlarmTipi VARCHAR2,
        p_Aciklama  VARCHAR2
    );

    PROCEDURE AlarmKapat(
        p_AlarmID NUMBER
    );

END Alarm_Pkg;

/* body */

CREATE OR REPLACE PACKAGE BODY Alarm_Pkg IS

    PROCEDURE RiskSkoruKontrolEt(p_MusteriID NUMBER) IS
        v_RiskSkoru NUMBER;
    BEGIN
        -- Müşteri risk skorunu Musteri_Pkg'den hesapla
        v_RiskSkoru := Musteri_Pkg.RiskSkoruHesapla(p_MusteriID);

        -- Risk skoru 60'ı aşıyorsa alarm oluştur
        IF v_RiskSkoru > 60 THEN
            AlarmEkle(
                p_MusteriID, 
                'YUKSEK RISK', 
                'Risk skoru 60 üzerinde, inceleme gerekli.'
            );
        END IF;
    END RiskSkoruKontrolEt;

    PROCEDURE AlarmEkle(
        p_MusteriID NUMBER,
        p_AlarmTipi VARCHAR2,
        p_Aciklama  VARCHAR2
    ) IS
    BEGIN
        -- Yeni alarm kaydı oluştur
        INSERT INTO Alarm (MusteriID, AlarmTipi, Aciklama)
        VALUES (p_MusteriID, p_AlarmTipi, p_Aciklama);
    END AlarmEkle;

    PROCEDURE AlarmKapat(p_AlarmID NUMBER) IS
    BEGIN
        -- İlgili alarmı kapalı duruma getir
        UPDATE Alarm 
           SET Durum = 'KAPANDI' 
         WHERE AlarmID = p_AlarmID;
    END AlarmKapat;

END Alarm_Pkg;

/* kodları çalıştırma*/

-- Risk Skoru hesaplayabilmek için Musteri Paketindeki RiskSkoruHesapla fonksiyonuna bakıp
-- Kredi tablosunda Durum bilgisi 'AKTIF' olan kredilerdeki müşterilerin hepsinin RiskSkoru nu incelemeye karar verdim
-- Öncelikle alarm durumundaki müşteriler için alarm kaydı oluşturacağız
-- bu koddan kontrol sağladık tablo boş geldi, yani hiç alarm durumunda müşteri yok 
-- 2000 tane dummy olarak alarm durumunda müşteri oluşturalım
-- Risk Skoru vade tarihi, sistem tarihinden küçük olan ve kalan borcun 0 dan büyük olduğu kredilerin sayısına göre hesaplama yapar.
-- Kredi tablosunu baz alır, o yüzden Kredi tablosunu update ettik.

DECLARE
    CURSOR c_Alarm_Musteriler IS
        SELECT DISTINCT MusteriID
          FROM (
                SELECT MusteriID
                  FROM Kredi
                 WHERE Durum = 'AKTIF'
                 ORDER BY DBMS_RANDOM.VALUE
               )
         WHERE ROWNUM <= 2000;

BEGIN
    FOR r IN c_Alarm_Musteriler LOOP
        
        -- Bu müşterinin tüm aktif kredilerini gecikmeye düşür
        UPDATE Kredi k
           SET k.VadeTarihi = SYSDATE - TRUNC(DBMS_RANDOM.VALUE(5, 60)), --random olarak 5 ya da 60 gün gecikme
               k.KalanBorc  = TRUNC(DBMS_RANDOM.VALUE(1000, 20000)) -- random olarak 1000-20000 arasında kalan borç
         WHERE k.MusteriID = r.MusteriID
           AND k.Durum = 'AKTIF';
    END LOOP;

    COMMIT;
END;
/

-- şimdi Kredi Durumu 'AKTIF' olan bütün müşteriler için alarm durumunu kontrol edelim
BEGIN
    FOR r IN (
        SELECT DISTINCT MusteriID
          FROM Kredi
         WHERE Durum = 'AKTIF'
    ) LOOP
        Alarm_Pkg.RiskSkoruKontrolEt(r.MusteriID);
    END LOOP;
END;
/

-- şimdi YUKSEK RISK olan kredilerin Alarmını kapatmak için random olarak 500 tanesinin borcunu 0 a çekeceğiz ve alarmı kapatacağız
DECLARE
    CURSOR c_Riskli_Alarmlar IS
        SELECT AlarmID, MusteriID
          FROM (
                SELECT AlarmID, MusteriID
                  FROM Alarm
                 WHERE Durum = 'AKTIF'
                   AND AlarmTipi = 'YUKSEK RISK'
                 ORDER BY DBMS_RANDOM.VALUE
               )
         WHERE ROWNUM <= 500;

BEGIN
    FOR r IN c_Riskli_Alarmlar LOOP

        -- Bu müşterinin tüm aktif kredilerinin borcunu sıfırla
        UPDATE Kredi k
           SET k.KalanBorc = 0
         WHERE k.MusteriID = r.MusteriID
           AND k.Durum = 'AKTIF';

        -- Alarmı kapat
        Alarm_Pkg.AlarmKapat(r.AlarmID);

    END LOOP;

    COMMIT;
END;
/


SELECT * FROM Alarm;


