/*
HesapNo: Her hesaba özel, otomatik artan birincil anahtar.
MusteriID: Hesabın bağlı olduğu müşteri kimliği (yabancı anahtar).
SubeID: Hesabın açıldığı şube kodu.
HesapTuru: Vadesiz, vadeli gibi hesap türü bilgisi.
Bakiye: Hesaptaki mevcut bakiye.
Limit: Hesap için belirlenen kredi limiti (varsayılan 10.000).
FaizOrani: Hesap için geçerli faiz oranı.
Durum: Hesabın durumu (AÇIK veya KAPALI).
OlusturmaTarihi: Hesabın açıldığı tarih.
*/

CREATE TABLE Hesap (
    HesapNo         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MusteriID       NUMBER       NOT NULL,
    SubeID          NUMBER       NOT NULL,
    HesapTuru       VARCHAR2(20) NOT NULL,
    Bakiye          NUMBER       DEFAULT 0,
    Limit           NUMBER       DEFAULT 10000,
    FaizOrani       NUMBER(5,2)  DEFAULT 1.5,
    Durum           VARCHAR2(20) DEFAULT 'AÇIK',
    OlusturmaTarihi DATE         DEFAULT SYSDATE,
    
    CONSTRAINT fk_hesap_musteri
        FOREIGN KEY (MusteriID) REFERENCES Musteri(MusteriID)
);


/*
HesapAc: Yeni bir hesap açar ve otomatik HesapNo döner.
BakiyeSorgula: Hesabın güncel bakiyesini getirir.
HesapKapat: Hesabı kapatır, yani durumunu KAPALI yapar.
BakiyeGuncelle: Hesabın bakiyesini artırır veya azaltır.
*/

CREATE OR REPLACE PACKAGE Hesap_Pkg IS

    PROCEDURE HesapAc(
        p_MusteriID       NUMBER,
        p_SubeID          NUMBER,
        p_HesapTuru       VARCHAR2,
        p_BaslangicBakiye NUMBER DEFAULT 0,
        o_HesapNo         OUT NUMBER
    );

    FUNCTION BakiyeSorgula(
        p_HesapNo NUMBER
    ) RETURN NUMBER;

    PROCEDURE HesapKapat(
        p_HesapNo NUMBER
    );

    PROCEDURE BakiyeGuncelle(
        p_HesapNo NUMBER, 
        p_Tutar   NUMBER
    );

END Hesap_Pkg;


/*
HesapAc prosedürü, ilgili müşteri ve şube bilgileriyle yeni bir hesap açar ve üretilen HesapNo’yu çıktı parametresi olarak verir.
BakiyeSorgula fonksiyonu, hesap bakiyesini sorgular; eğer hesap bulunamazsa -1 döndürür.
HesapKapat prosedürü hesabı kapatır (durumu KAPALI yapar).
BakiyeGuncelle prosedürü ise bakiye üzerinde artış veya azalış işlemi yapar (örneğin para yatırma veya çekme).
*/

CREATE OR REPLACE PACKAGE BODY Hesap_Pkg IS

    PROCEDURE HesapAc(
        p_MusteriID       NUMBER,
        p_SubeID          NUMBER,
        p_HesapTuru       VARCHAR2,
        p_BaslangicBakiye NUMBER DEFAULT 0,
        o_HesapNo         OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO Hesap (MusteriID, SubeID, HesapTuru, Bakiye)
        VALUES (p_MusteriID, p_SubeID, p_HesapTuru, p_BaslangicBakiye)
        RETURNING HesapNo INTO o_HesapNo;
    END HesapAc;

    FUNCTION BakiyeSorgula(
        p_HesapNo NUMBER
    ) RETURN NUMBER IS
        v_Bakiye NUMBER;
    BEGIN
        SELECT Bakiye 
          INTO v_Bakiye 
          FROM Hesap 
         WHERE HesapNo = p_HesapNo;
         
        RETURN v_Bakiye;
        
    EXCEPTION
        WHEN NO_DATA_FOUND THEN 
            RETURN -1;   -- Hesap bulunamadıysa -1 döner
    END BakiyeSorgula;

    PROCEDURE HesapKapat(
        p_HesapNo NUMBER
    ) IS
    BEGIN
        UPDATE Hesap 
           SET Durum = 'KAPALI' 
         WHERE HesapNo = p_HesapNo;
    END HesapKapat;

    PROCEDURE BakiyeGuncelle(
        p_HesapNo NUMBER, 
        p_Tutar   NUMBER
    ) IS
    BEGIN
        UPDATE Hesap 
           SET Bakiye = ROUND(Bakiye + p_Tutar, 2)
         WHERE HesapNo = p_HesapNo;
    END BakiyeGuncelle;

END Hesap_Pkg;
/

/* kodları çalıştırma*/

-- 8500 aktif müşteri için HesapAc prosedürü ile hesap açma
DECLARE
    v_HesapNo NUMBER;
BEGIN
    FOR r IN (
        SELECT MusteriID
        FROM Musteri
        WHERE Durum = 'AKTIF'
    ) LOOP
        Hesap_Pkg.HesapAc(
            p_MusteriID       => r.MusteriID,
            p_SubeID          => TRUNC(DBMS_RANDOM.VALUE(1, 15)),
            p_HesapTuru       => 'VADESIZ',
            p_BaslangicBakiye => TRUNC(DBMS_RANDOM.VALUE(0, 2000000)),
            o_HesapNo         => v_HesapNo
        );
    END LOOP;

    COMMIT;
END;
/

-- 500 hesabı HesapKapat prosedürü ile kapatma ,
DECLARE
    v_HesapNo NUMBER;
BEGIN
    FOR r IN (
        SELECT HesapNo
        FROM (
            SELECT HesapNo
            FROM Hesap
            WHERE Durum = 'AÇIK'
            ORDER BY DBMS_RANDOM.VALUE
        )
        WHERE ROWNUM <= 500
    ) LOOP
        Hesap_Pkg.HesapKapat(r.HesapNo);
    END LOOP;

    COMMIT;
END;
/

-- random 1500 hesabın BakiyeGuncelle prosedürü ile Bakiye bilgisini güncelleme
DECLARE
    v_HesapNo NUMBER;
BEGIN
    FOR r IN (
        SELECT HesapNo
        FROM (
            SELECT HesapNo
            FROM Hesap
            ORDER BY DBMS_RANDOM.VALUE
        )
        WHERE ROWNUM <= 1500
    ) LOOP
        Hesap_Pkg.BakiyeGuncelle(
            p_HesapNo => r.HesapNo,
            p_Tutar   => TRUNC(DBMS_RANDOM.VALUE(-1000, 5000))
        );
    END LOOP;

    COMMIT;
END;
/



-- İlk 5 hesabın BakiyeSorgula fonksiyonu ile bakiye bilgisini sorgulama
SET SERVEROUTPUT ON;

DECLARE
    v_Bakiye NUMBER;
BEGIN
    FOR r IN (
        SELECT HesapNo
        FROM Hesap
        WHERE ROWNUM <= 5
    ) LOOP
        v_Bakiye := Hesap_Pkg.BakiyeSorgula(r.HesapNo);
        DBMS_OUTPUT.PUT_LINE('HesapNo: ' || r.HesapNo || ' Bakiye: ' || v_Bakiye);
    END LOOP;
END;
/

-- 1 hesabın BakiyeSorgula fonksiyonu ile bakiye bilgisini sorgulama
DECLARE
    v_Bakiye NUMBER;
    v_HesapNo NUMBER := 80;  -- örnek hesap numarası
BEGIN
    v_Bakiye := Hesap_Pkg.BakiyeSorgula(v_HesapNo);
    DBMS_OUTPUT.PUT_LINE('HesapNo: ' || v_HesapNo || ' Bakiye: ' || v_Bakiye);
END;
/

SELECT * FROM Hesap
