/*
KartNo: Her kart için benzersiz numara
MusteriID: Kart sahibine ait müşteri ID
HesapNo: Kartın bağlı olduğu hesap
KartTuru: 'KREDI' veya 'DEBIT'
Limit: Kartın toplam limiti
KalanLimit: Kullanılabilir limit
SonKullanmaTarihi: Kartın son geçerlilik tarihi
Durum: Kart durumu (AKTIF, IPTAL)
KartCvc: Kart güvenlik kodu
*/

CREATE TABLE Kart (
    KartNo            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    MusteriID         NUMBER       NOT NULL,                                
    HesapNo           NUMBER       NOT NULL,                                
    KartTuru          VARCHAR2(10) NOT NULL,                                
    Limit             NUMBER       DEFAULT 5000,                            
    KalanLimit        NUMBER       DEFAULT 5000,                            
    SonKullanmaTarihi DATE         NOT NULL,                                
    Durum             VARCHAR2(20) DEFAULT 'AKTIF',                         
    KartCvc           CHAR(3)      NOT NULL,                                
    
    CONSTRAINT fk_kart_musteri
        FOREIGN KEY (MusteriID) REFERENCES Musteri(MusteriID),
    CONSTRAINT fk_kart_hesap
        FOREIGN KEY (HesapNo) REFERENCES Hesap(HesapNo)
);

/*
KartIslemID: İşlem kimliği
KartNo: İşlem yapılan kart
IslemTipi: 'HARCA', 'TAKSIT', 'IADE' vb.
Tutar: İşlem tutarı
IslemTarihi: İşlem tarihi
Aciklama: İşlem açıklaması
*/

CREATE TABLE KartIslem (
    KartIslemID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    KartNo      NUMBER       NOT NULL,                                
    IslemTipi   VARCHAR2(20) NOT NULL,                               
    Tutar       NUMBER       NOT NULL,                                
    IslemTarihi DATE         DEFAULT SYSDATE,                         
    Aciklama    VARCHAR2(200),                                        
    
    CONSTRAINT fk_kartislem_kart
        FOREIGN KEY (KartNo) REFERENCES Kart(KartNo) 
);

/*
KartAc: Yeni kart kaydı oluşturur (kredi veya debit)
KartLimitGuncelle: Kart limitini düşürür (harcama sonrası)
KartIslemYap: Kart işlemi yapar (harcama, taksit, iade vb.)
KartBakiyeSorgula: Kartın mevcut limitini sorgular
KartKapat: Kartı iptal eder (kapatır)
*/

CREATE OR REPLACE PACKAGE Kart_Pkg IS

    PROCEDURE KartAc(
        p_MusteriID         NUMBER,
        p_HesapNo           NUMBER,
        p_KartTuru          VARCHAR2,
        p_Limit             NUMBER DEFAULT 5000,
        p_SonKullanmaTarihi DATE,
        p_KartCvc           CHAR,
        o_KartNo            OUT NUMBER
    );

    PROCEDURE KartLimitGuncelle(
        p_KartNo NUMBER, 
        p_Tutar  NUMBER
    );

    PROCEDURE KartIslemYap(
        p_KartNo    NUMBER,
        p_Tutar     NUMBER,
        p_IslemTipi VARCHAR2,
        p_Aciklama  VARCHAR2 DEFAULT NULL
    );

    FUNCTION KartBakiyeSorgula(
        p_KartNo NUMBER
    ) RETURN NUMBER;

    PROCEDURE KartKapat(
        p_KartNo NUMBER
    );

END Kart_Pkg;

/*body*/
CREATE OR REPLACE PACKAGE BODY Kart_Pkg IS

    PROCEDURE KartAc(
        p_MusteriID         NUMBER,
        p_HesapNo           NUMBER,
        p_KartTuru          VARCHAR2,
        p_Limit             NUMBER DEFAULT 5000,
        p_SonKullanmaTarihi DATE,
        p_KartCvc           CHAR,
        o_KartNo            OUT NUMBER
    ) IS
    BEGIN
        -- Yeni kart kaydı oluştur
        INSERT INTO Kart (MusteriID, HesapNo, KartTuru, Limit, KalanLimit, SonKullanmaTarihi, KartCvc)
        VALUES (p_MusteriID, p_HesapNo, p_KartTuru, p_Limit, p_Limit, p_SonKullanmaTarihi, p_KartCvc)
        RETURNING KartNo INTO o_KartNo;
    END KartAc;

    PROCEDURE KartLimitGuncelle(
        p_KartNo NUMBER, 
        p_Tutar  NUMBER
    ) IS
        v_KalanLimit NUMBER;
    BEGIN
        SELECT KalanLimit 
        INTO   v_KalanLimit 
        FROM   Kart 
        WHERE  KartNo = p_KartNo;
        -- Limit yetersizse hata fırlat
        IF v_KalanLimit < p_Tutar THEN
            RAISE_APPLICATION_ERROR(-20040, 'Kart limiti yetersiz.');
        END IF;

        -- Kalan limiti güncelle
        UPDATE Kart 
        SET    KalanLimit = KalanLimit - p_Tutar 
        WHERE  KartNo = p_KartNo;
    END KartLimitGuncelle;

    PROCEDURE KartIslemYap(
        p_KartNo    NUMBER,
        p_Tutar     NUMBER,
        p_IslemTipi VARCHAR2,
        p_Aciklama  VARCHAR2 DEFAULT NULL
    ) IS
    BEGIN
        -- Kart limiti güncellenir
        KartLimitGuncelle(p_KartNo, p_Tutar);

        -- İşlem kaydı oluşturulur
        INSERT INTO KartIslem (KartNo, IslemTipi, Tutar, Aciklama)
        VALUES (p_KartNo, p_IslemTipi, p_Tutar, NVL(p_Aciklama, 'Kart işlemi yapıldı'));
    END KartIslemYap;

    FUNCTION KartBakiyeSorgula(
        p_KartNo NUMBER
    ) RETURN NUMBER IS
        v_KalanLimit NUMBER;
    BEGIN
        SELECT KalanLimit 
        INTO   v_KalanLimit 
        FROM   Kart 
        WHERE  KartNo = p_KartNo;
        
        RETURN v_KalanLimit;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN -1; -- Kart bulunamazsa -1 döner
    END KartBakiyeSorgula;

    PROCEDURE KartKapat(
        p_KartNo NUMBER
    ) IS
    BEGIN
        -- Kart durumu "İPTAL" yapılır
        UPDATE Kart 
        SET    Durum = 'IPTAL' 
        WHERE  KartNo = p_KartNo;
    END KartKapat;

END Kart_Pkg;

/* kodları çalıştırma*/

-- 10 000 müşterimiz vardı, bunun 1500 ü aktif değildi
-- Bu yüzden geri kalan 8500 müşteri için 8500 hesap açtık
-- Bu 8500 hesabın 500 ünü KAPALI hale getirmiştik.
-- Geri kalan 8000 açık hesap üzerinde işlemler yapmak istiyoruz
-- 6000 adet kart açma işlemi yapmak istiyoruz.
-- Bu random olarak seçilmiş 6000 hesaba 
-- Random olarak kart açma, kart işlem yapma gibi prosedürleri uyguluyoruz
-- Sonra 6000 açık kartın random olarak 2000 tanesine kart kapatma işlemi uyguluyoruz.

-- Random 6000 kişi için kart açma 
DECLARE
    CURSOR c_AktifMusteriler IS
        SELECT     m.MusteriID, h.HesapNo
        FROM       Musteri m
        INNER JOIN Hesap h  ON  h.MusteriID = m.MusteriID        
        WHERE      m.Durum = 'AKTIF' AND h.Durum = 'AÇIK'
        ORDER BY   DBMS_RANDOM.VALUE; -- RANDOM SIRALAMA

    v_Sayac   NUMBER := 0;
    v_KartNo  NUMBER;
BEGIN
    DBMS_RANDOM.SEED(TO_NUMBER(TO_CHAR(SYSDATE, 'SSSSS')));

    FOR r IN c_AktifMusteriler LOOP
        v_Sayac := v_Sayac + 1;

        IF v_Sayac <= 6000 THEN

            -- Kart aç
            Kart_Pkg.KartAc(
                p_MusteriID         => r.MusteriID,
                p_HesapNo           => r.HesapNo,
                p_KartTuru          => CASE WHEN DBMS_RANDOM.VALUE < 0.5 THEN 'KREDI' ELSE 'BANKA' END,
                p_Limit             => 5000,
                p_SonKullanmaTarihi => ADD_MONTHS(SYSDATE, 36),
                p_KartCvc           => LPAD(TRUNC(DBMS_RANDOM.VALUE(100, 999)), 3, '0'),
                o_KartNo            => v_KartNo
            );

        END IF;

    END LOOP;

    COMMIT;
END;
/

-- Random olarak kart işlemleri yapma
DECLARE
    CURSOR c_AktifMusteriler IS
        SELECT   k.MusteriID, k.KartNo, k.KalanLimit
        FROM     Kart k
        WHERE    k.Durum = 'AKTIF'
        ORDER BY DBMS_RANDOM.VALUE;

    v_Tutar       NUMBER;
    v_IslemTipi   VARCHAR2(20);
BEGIN
    DBMS_RANDOM.SEED(TO_NUMBER(TO_CHAR(SYSDATE, 'SSSSS')));

    FOR r IN c_AktifMusteriler LOOP
            
            CASE 
                WHEN DBMS_RANDOM.VALUE < 0.60 THEN  -- HARCA -> pozitif
                    v_Tutar     := TRUNC(DBMS_RANDOM.VALUE(1, r.KalanLimit * 0.3));
                    v_IslemTipi := 'HARCA';
                WHEN DBMS_RANDOM.VALUE < 0.85 THEN  -- TAKSIT -> pozitif
                    v_Tutar     := TRUNC(DBMS_RANDOM.VALUE(1, r.KalanLimit * 0.3));
                    v_IslemTipi := 'TAKSIT';
                ELSE                                 -- IADE -> negatif
                    v_Tutar     := -TRUNC(DBMS_RANDOM.VALUE(1, 3000));
                    v_IslemTipi := 'IADE';
            END CASE;
        
            Kart_Pkg.KartIslemYap(
                p_KartNo      => r.KartNo,
                p_Tutar       => v_Tutar,
                p_IslemTipi   => v_IslemTipi,
                p_Aciklama    => 'EFT'
            );
    END LOOP;

    COMMIT;
END;
/

-- Random olarak seçilen 2000 kişi için kart kapatma
DECLARE
    CURSOR c_AktifMusteriler IS
        SELECT   k.MusteriID, k.KartNo
        FROM     Kart k
        WHERE    k.Durum = 'AKTIF'
        ORDER BY DBMS_RANDOM.VALUE;

    v_Sayac NUMBER := 0;
BEGIN
    DBMS_RANDOM.SEED(TO_NUMBER(TO_CHAR(SYSDATE, 'SSSSS')));

    FOR r IN c_AktifMusteriler LOOP
        v_Sayac := v_Sayac + 1;

        IF v_Sayac <= 2000 THEN

            Kart_Pkg.KartKapat(r.KartNo);

        END IF;

    END LOOP;

    COMMIT;
END;
/

-- İlk 5 kartın KartBakiyeSorgula fonksiyonu ile bakiye bilgisini sorgulama
SET SERVEROUTPUT ON;

DECLARE
    v_KartBakiye NUMBER;
BEGIN
    FOR r IN (
        SELECT KartNo
        FROM Kart
        WHERE ROWNUM <= 5
    ) LOOP
        v_KartBakiye := Kart_Pkg.KartBakiyeSorgula(r.KartNo);
        DBMS_OUTPUT.PUT_LINE('KartNo: ' || r.KartNo || ' KartBakiye: ' || v_KartBakiye);
    END LOOP;
END;
/

-- 1 hesabın KartBakiyeSorgula fonksiyonu ile bakiye bilgisini sorgulama
DECLARE
    v_KartBakiye NUMBER;
    v_KartNo NUMBER := 4480;  -- örnek kart numarası
BEGIN
    v_KartBakiye := Kart_Pkg.KartBakiyeSorgula(v_KartNo);
    DBMS_OUTPUT.PUT_LINE('KartNo: ' || v_KartNo || ' KartBakiye: ' || v_KartBakiye);
END;
/

SELECT * FROM Kart;
SELECT * FROM KartIslem;
