/*
KullaniciID: Her kullanıcı için benzersiz kimlik
KullaniciAdi: Sisteme girişte kullanılan benzersiz kullanıcı adı
Sifre: Kullanıcının şifre bilgisi
Rol: Kullanıcının sistemdeki rolü (ADMIN, PERSONEL, MUSTERI)
Durum: Kullanıcının aktiflik durumu (AKTIF, PASIF)
*/

CREATE TABLE Kullanici (
    KullaniciID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    KullaniciAdi VARCHAR2(30)  UNIQUE NOT NULL,
    Sifre        VARCHAR2(100) NOT NULL,
    Rol          VARCHAR2(20)  NOT NULL, -- ADMIN, PERSONEL, MUSTERI
    Durum        VARCHAR2(20)  DEFAULT 'AKTIF'
);

/*
KullaniciEkle: Yeni kullanıcı ekler ve kimliğini döner.
KullaniciDogrula: Giriş yapan kullanıcının kimlik doğrulamasını yapar.
KullaniciPasifEt: İlgili kullanıcı hesabını devre dışı bırakır.
*/

CREATE OR REPLACE PACKAGE Kullanici_Pkg IS

    PROCEDURE KullaniciEkle(
        p_KullaniciAdi VARCHAR2,
        p_Sifre        VARCHAR2,
        p_Rol          VARCHAR2,
        o_KullaniciID  OUT NUMBER
    );

    FUNCTION KullaniciDogrula(
        p_KullaniciAdi VARCHAR2,
        p_Sifre        VARCHAR2
    ) RETURN BOOLEAN;

    PROCEDURE KullaniciPasifEt(
        p_KullaniciID NUMBER
    );

END Kullanici_Pkg;

/* body */

CREATE OR REPLACE PACKAGE BODY Kullanici_Pkg IS

    -- Yeni kullanıcı ekler
    PROCEDURE KullaniciEkle(
        p_KullaniciAdi VARCHAR2,
        p_Sifre        VARCHAR2,
        p_Rol          VARCHAR2,
        o_KullaniciID  OUT NUMBER
    ) IS
    BEGIN
        INSERT INTO Kullanici (KullaniciAdi, Sifre, Rol)
        VALUES (p_KullaniciAdi, p_Sifre, p_Rol)
        RETURNING KullaniciID INTO o_KullaniciID;
    END KullaniciEkle;

    -- Giriş yapan kullanıcının doğruluğunu kontrol eder
    FUNCTION KullaniciDogrula(
        p_KullaniciAdi VARCHAR2,
        p_Sifre        VARCHAR2
    ) RETURN BOOLEAN IS
        v_Count NUMBER;
    BEGIN
        SELECT COUNT(*) 
          INTO v_Count 
          FROM Kullanici
         WHERE KullaniciAdi = p_KullaniciAdi 
           AND Sifre = p_Sifre 
           AND Durum = 'AKTIF';
        RETURN (v_Count > 0);
    END KullaniciDogrula;

    -- Kullanıcı hesabını pasif hale getirir
    PROCEDURE KullaniciPasifEt(
        p_KullaniciID NUMBER
    ) IS
    BEGIN
        UPDATE Kullanici 
           SET Durum = 'PASIF' 
         WHERE KullaniciID = p_KullaniciID;
    END KullaniciPasifEt;

END Kullanici_Pkg;

/* kodları çalıştırma*/
-- Tüm müşteriler için 'MUSTERI' rolünde KullaniciEkle prosedürü ile kullanıcı oluşturuyoruz. 
-- Sonra 5 tane 'ADMIN', 22 'PERSONEL' rolü için kullanıcı oluşturuyoruz.
-- Sonra KullaniciPasifEt prosedürü ile 'PASIF' müşteriler için, kullanıcıları 'PASIF' e çekiyoruz,
-- 'PERSONEL' ve 'ADMIN' den de 2 şer kullanıcı 'PASIF' e çekiyoruz.

DECLARE
    CURSOR c_Musteriler IS
        SELECT MusteriID, Ad, Soyad
          FROM Musteri
         ORDER BY MusteriID;

    v_KullaniciID   NUMBER;
    v_AdminSayac    NUMBER := 0;
    v_PersonelSayac NUMBER := 0;

BEGIN
    -- Tüm müşteriler için MUSTERI rolünde kullanıcı oluşturma
    FOR r IN c_Musteriler LOOP
        Kullanici_Pkg.KullaniciEkle(
            p_KullaniciAdi => LOWER(r.Ad || r.Soyad || r.MusteriID),
            p_Sifre        => SUBSTR(DBMS_RANDOM.STRING('A', 20), 1, 8),
            p_Rol          => 'MUSTERI',
            o_KullaniciID  => v_KullaniciID
        );
    END LOOP;

    -- 5 adet ADMIN kullanıcı oluşturma
    FOR i IN 1 .. 5 LOOP
        Kullanici_Pkg.KullaniciEkle(
            p_KullaniciAdi => 'admin_control_' || i,
            p_Sifre        => SUBSTR(DBMS_RANDOM.STRING('A', 20), 1, 8),
            p_Rol          => 'ADMIN',
            o_KullaniciID  => v_KullaniciID
        );
    END LOOP;

    -- 22 adet PERSONEL kullanıcı oluşturma
    FOR i IN 1 .. 22 LOOP
        Kullanici_Pkg.KullaniciEkle(
            p_KullaniciAdi => 'personel_ops_' || i,
            p_Sifre        => SUBSTR(DBMS_RANDOM.STRING('A', 20), 1, 8),
            p_Rol          => 'PERSONEL',
            o_KullaniciID  => v_KullaniciID
        );
    END LOOP;
    
    COMMIT;
END;
/

-- PASIF yapma
DECLARE
    CURSOR c_PasifMusteriler IS
        SELECT m.MusteriID
          FROM Musteri m
         WHERE m.Durum = 'PASIF';

BEGIN
    -- PASIF müşterilerin kullanıcılarını pasif yapma
    FOR r IN c_PasifMusteriler LOOP
        UPDATE Kullanici
           SET Durum = 'PASIF'
         WHERE SUBSTR(KullaniciAdi, -5) = TO_CHAR(r.MusteriID)
           AND Rol = 'MUSTERI';
    END LOOP;

    -- ADMIN’den random 2 kullanıcıyı pasif yapma
    FOR r IN (
        SELECT KullaniciID
          FROM Kullanici
         WHERE Rol = 'ADMIN'
         ORDER BY DBMS_RANDOM.VALUE
         FETCH FIRST 2 ROWS ONLY
    ) LOOP
        UPDATE Kullanici
           SET Durum = 'PASIF'
         WHERE KullaniciID = r.KullaniciID;
    END LOOP;

    -- PERSONEL’den random 2 kullanıcıyı pasif yapma
    FOR r IN (
        SELECT KullaniciID
          FROM Kullanici
         WHERE Rol = 'PERSONEL'
         ORDER BY DBMS_RANDOM.VALUE
         FETCH FIRST 2 ROWS ONLY
    ) LOOP
        UPDATE Kullanici
           SET Durum = 'PASIF'
         WHERE KullaniciID = r.KullaniciID;
    END LOOP;

    COMMIT;
END;
/

-- Kullanıcı Doğrulama fonksiyonunu çalıştıralım
SET SERVEROUTPUT ON;

DECLARE
    v_Sonuc BOOLEAN;
BEGIN
    v_Sonuc := Kullanici_Pkg.KullaniciDogrula(
                    p_KullaniciAdi => 'gamzeçelik20020',
                    p_Sifre        => 'NXrCVHqd'
               );

    IF v_Sonuc THEN
        DBMS_OUTPUT.PUT_LINE('TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FALSE');
    END IF;
END;
/

SELECT * FROM Kullanici