/*
LogID: Her log kaydına ait benzersiz kimlik numarası (birincil anahtar).
IslemTipi: Gerçekleştirilen işlemin türü (örneğin: HATA, BİLGİ, UYARI, BAŞARILI).
Aciklama: İşlem veya hataya ilişkin açıklama metni.
Kaynak: Log kaydını üreten paket veya prosedürün adı.
HataKodu: Oracle hata kodu veya uygulama tarafından üretilen özel hata kodu.
KullaniciID: İşlemi gerçekleştiren kullanıcıya ait kimlik numarası.
Tarih: Log kaydının oluşturulduğu tarih (varsayılan olarak sistem tarihi atanır).
EkVeri: JSON formatında ek veri, işlemle ilgili detaylı bilgiler (örneğin { "HesapNo":101, "Tutar":500 }).
*/

CREATE TABLE Log (
    LogID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IslemTipi    VARCHAR2(50),      
    Aciklama     VARCHAR2(400),      
    Kaynak       VARCHAR2(100),      
    HataKodu     VARCHAR2(20),       
    KullaniciID  NUMBER,             
    Tarih        DATE DEFAULT SYSDATE,
    EkVeri       CLOB                
);

/*
LogEkle: Genel log ekleme prosedürü. İşlem tipi (HATA, BİLGİ, UYARI, BAŞARILI), açıklama, kaynak paket/prosedür, hata kodu, kullanıcı kimliği ve JSON formatında ek veriyi kaydeder.
LogHata: Hata logu ekler. Açıklama, hata kodu ve kaynağı parametre olarak alır. İşlem tipi otomatik olarak 'HATA' olarak kaydedilir.
LogBilgi: Bilgi logu ekler. Açıklama ve kaynağı parametre olarak alır. İşlem tipi otomatik olarak 'BİLGİ' olarak kaydedilir.
LogUyari: Uyarı logu ekler. Açıklama ve kaynağı parametre olarak alır. İşlem tipi otomatik olarak 'UYARI' olarak kaydedilir.
*/

CREATE OR REPLACE PACKAGE Log_Pkg IS
    PROCEDURE LogEkle(
        p_IslemTipi   VARCHAR2,
        p_Aciklama    VARCHAR2,
        p_Kaynak      VARCHAR2 DEFAULT NULL,
        p_HataKodu    VARCHAR2 DEFAULT NULL,
        p_KullaniciID NUMBER   DEFAULT NULL,
        p_EkVeri      CLOB     DEFAULT NULL
    );

    PROCEDURE LogHata(
        p_Aciklama    VARCHAR2, 
        p_HataKodu    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    );
    
    PROCEDURE LogBilgi(
        p_Aciklama    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    );
    
    PROCEDURE LogUyari(
        p_Aciklama    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    );
    
END Log_Pkg;
/

/* body */

CREATE OR REPLACE PACKAGE BODY Log_Pkg IS
    PROCEDURE LogEkle(
        p_IslemTipi   VARCHAR2,
        p_Aciklama    VARCHAR2,
        p_Kaynak      VARCHAR2 DEFAULT NULL,
        p_HataKodu    VARCHAR2 DEFAULT NULL,
        p_KullaniciID NUMBER   DEFAULT NULL,
        p_EkVeri      CLOB     DEFAULT NULL
    ) IS
        PRAGMA AUTONOMOUS_TRANSACTION;
    BEGIN
        INSERT INTO Log (IslemTipi, Aciklama, Kaynak, HataKodu, KullaniciID, EkVeri, Tarih)
        VALUES (p_IslemTipi, p_Aciklama, p_Kaynak, p_HataKodu, p_KullaniciID, p_EkVeri, SYSDATE);
        COMMIT;
    END LogEkle;

    PROCEDURE LogHata(
        p_Aciklama    VARCHAR2,
        p_HataKodu    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    ) IS
    BEGIN
        LogEkle('HATA', p_Aciklama, p_Kaynak, p_HataKodu, p_KullaniciID);
    END;

    PROCEDURE LogBilgi(
        p_Aciklama    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    ) IS
    BEGIN
        LogEkle('BİLGİ', p_Aciklama, p_Kaynak, NULL, p_KullaniciID);
    END;

    PROCEDURE LogUyari(
        p_Aciklama    VARCHAR2, 
        p_Kaynak      VARCHAR2, 
        p_KullaniciID NUMBER DEFAULT NULL
    ) IS
    BEGIN
        LogEkle('UYARI', p_Aciklama, p_Kaynak, NULL, p_KullaniciID);
    END;
END Log_Pkg;
/

-- Trigger larla logların her modül için otomatik olarak çalışmasını sağlayalım
--müsteri
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_musteri_log
        AFTER INSERT OR UPDATE ON Musteri
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni müşteri eklendi, ID: ''||:NEW.MusteriID, ''Musteri_Tablosu'', :NEW.MusteriID);
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Müşteri güncellendi, ID: ''||:NEW.MusteriID, ''Musteri_Tablosu'', :NEW.MusteriID);
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Musteri_Tablosu'');
        END;
    ';
END;
/

--hesap
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_hesap_log
        AFTER INSERT OR UPDATE ON Hesap
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni hesap açıldı, HesapNo: ''||:NEW.HesapNo, ''Hesap_Tablosu'', :NEW.MusteriID);
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Hesap güncellendi, HesapNo: ''||:NEW.HesapNo, ''Hesap_Tablosu'', :NEW.MusteriID);
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Hesap_Tablosu'');
        END;
    ';
END;
/

--islem
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_islem_log
        AFTER INSERT OR UPDATE ON Islem
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni işlem eklendi, IslemID: ''||:NEW.IslemID, ''Islem_Tablosu'', :NEW.HesapNo);
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''İşlem güncellendi, IslemID: ''||:NEW.IslemID, ''Islem_Tablosu'', :NEW.HesapNo);
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Islem_Tablosu'');
        END;
    ';
END;
/

--kredi
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_kredi_log
        AFTER INSERT OR UPDATE ON Kredi
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni kredi açıldı, KrediID: ''||:NEW.KrediID, ''Kredi_Tablosu'', :NEW.MusteriID);
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Kredi güncellendi, KrediID: ''||:NEW.KrediID, ''Kredi_Tablosu'', :NEW.MusteriID);
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Kredi_Tablosu'');
        END;
    ';
END;
/

--kart
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_kart_log
        AFTER INSERT OR UPDATE ON Kart
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni kart açıldı, KartNo: ''||:NEW.KartNo, ''Kart_Tablosu'', :NEW.MusteriID);
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Kart güncellendi, KartNo: ''||:NEW.KartNo, ''Kart_Tablosu'', :NEW.MusteriID);
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Kart_Tablosu'');
        END;
    ';
END;
/

--faiz
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_faiz_log
        AFTER INSERT OR UPDATE ON Faiz
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni faiz kaydı eklendi, FaizID: ''||:NEW.FaizID, ''Faiz_Tablosu'');
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Faiz güncellendi, FaizID: ''||:NEW.FaizID, ''Faiz_Tablosu'');
            END IF;
            EXCEPTION
                WHEN OTHERS THEN
                    Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Faiz_Tablosu'');
        END;
    ';
END;
/

--alarm
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_alarm_log
        AFTER INSERT OR UPDATE OR DELETE ON Alarm
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni alarm eklendi, AlarmID: ''||:NEW.AlarmID, ''Alarm_Tablosu'');
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Alarm güncellendi, AlarmID: ''||:NEW.AlarmID, ''Alarm_Tablosu'');
            ELSIF DELETING THEN
                Log_Pkg.LogUyari(''Alarm silindi, AlarmID: ''||:OLD.AlarmID, ''Alarm_Tablosu'');
        END IF;
        EXCEPTION
            WHEN OTHERS THEN
                Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Alarm_Tablosu'');
        END;
    ';
END;
/

--swift
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_swift_log
        AFTER INSERT OR UPDATE ON Swift
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni SWIFT transfer eklendi, SwiftID: ''||:NEW.SwiftID, ''Swift_Tablosu'');
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''SWIFT transfer güncellendi, SwiftID: ''||:NEW.SwiftID, ''Swift_Tablosu'');
        END IF;
        EXCEPTION
            WHEN OTHERS THEN
                Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Swift_Tablosu'');
        END;
    ';
END;
/

--kullanici
BEGIN
    EXECUTE IMMEDIATE '
        CREATE OR REPLACE TRIGGER trg_kullanici_log
        AFTER INSERT OR UPDATE OR DELETE ON Kullanici
        FOR EACH ROW
        BEGIN
            IF INSERTING THEN
                Log_Pkg.LogBilgi(''Yeni kullanıcı eklendi, KullaniciID: ''||:NEW.KullaniciID, ''Kullanici_Tablosu'');
            ELSIF UPDATING THEN
                Log_Pkg.LogBilgi(''Kullanıcı güncellendi, KullaniciID: ''||:NEW.KullaniciID, ''Kullanici_Tablosu'');
            ELSIF DELETING THEN
                Log_Pkg.LogUyari(''Kullanıcı silindi, KullaniciID: ''||:OLD.KullaniciID, ''Kullanici_Tablosu'');
        END IF;
        EXCEPTION
            WHEN OTHERS THEN
                Log_Pkg.LogHata(SQLERRM, SQLCODE, ''Kullanici_Tablosu'');
        END;
    ';
END;
/

SELECT * FROM Log