/*
SwiftID: Her swift kaydı için benzersiz kimlik
GonderenHesapNo: İşlemi başlatan müşteriye ait hesap numarası
AliciIBAN: Paranın gönderileceği alıcının uluslararası IBAN bilgisi
Tutar: Gönderilen döviz tutarı (işlemde kullanılan ana miktar)
Kur: İşlem sırasında uygulanan döviz kuru
IslemTarihi: Swift talimatının oluşturulduğu tarih
Durum: İşlemin mevcut durumu (PENDING, COMPLETED)
*/

CREATE TABLE SwiftMesaj (
    SwiftID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    GonderenHesapNo NUMBER       NOT NULL,
    AliciIBAN       VARCHAR2(34) NOT NULL,
    Tutar           NUMBER       NOT NULL,
    Kur             NUMBER(10,4) NOT NULL,
    IslemTarihi     DATE         DEFAULT SYSDATE,
    Durum           VARCHAR2(20) DEFAULT 'PENDING'
);

/*
SwiftTransfer: Bir hesaptan uluslararası IBAN’a para gönderir.
KurGuncelle: Döviz kurunu sistem genelinde günceller.
*/

CREATE OR REPLACE PACKAGE Swift_Pkg IS

    PROCEDURE SwiftTransfer(
        p_GonderenHesapNo NUMBER,
        p_AliciIBAN       VARCHAR2,
        p_Tutar           NUMBER
    );

    PROCEDURE KurGuncelle(
        p_YeniKur NUMBER
    );

END Swift_Pkg;

/*
İşlem sırasında önce ilgili hesaptan para düşülür (Islem_Pkg.ParaCek) ve ardından yeni bir SWIFT mesajı oluşturulur.
Kur değişimi merkezi bir değişkende (v_Kur) tutulur ve gerektiğinde KurGuncelle prosedürüyle dinamik olarak değiştirilir.
*/

CREATE OR REPLACE PACKAGE BODY Swift_Pkg IS

    -- Döviz kuru örneği (TRY/USD)
    v_Kur NUMBER(10,4) := 42.69; 

    PROCEDURE SwiftTransfer(
        p_GonderenHesapNo NUMBER,
        p_AliciIBAN       VARCHAR2,
        p_Tutar           NUMBER
    ) IS
    BEGIN
        -- Gönderen hesaptan tutar düşülür
        Islem_Pkg.ParaCek(p_GonderenHesapNo, p_Tutar);

        -- SWIFT mesaj kaydı oluşturulur
        INSERT INTO SwiftMesaj (GonderenHesapNo, AliciIBAN, Tutar, Kur, Durum)
        VALUES (p_GonderenHesapNo, p_AliciIBAN, p_Tutar, v_Kur, 'COMPLETED');
    END SwiftTransfer;

    PROCEDURE KurGuncelle(p_YeniKur NUMBER) IS
    BEGIN
        -- Güncel döviz kuru sistemde tutulur
        v_Kur := p_YeniKur;
    END KurGuncelle;

END Swift_Pkg;

/* kodları çalıştırma*/
-- Random seçtiğimiz 2000 AÇIK Hesaptan, önce 1500 tanesine random olarak eski kurdan swift yapsın,
-- Sonra 500 tanesine random kur güncelleyip, swift işlemi yapsın
-- GönderenHesap taki bakiye, input tutardan düşük olmasın.

DECLARE
    CURSOR c_Hesaplar IS
        SELECT HesapNo, Bakiye
          FROM (
                SELECT HesapNo, Bakiye
                  FROM Hesap
                 WHERE Durum = 'AÇIK'
                 ORDER BY DBMS_RANDOM.VALUE
               )
         WHERE ROWNUM <= 2000;

    v_sayac   NUMBER := 0;
    v_yeniKur NUMBER(10,4);
    v_tutar   NUMBER;
BEGIN
    FOR r IN c_Hesaplar LOOP
        v_sayac := v_sayac + 1;

        -- Random tutarı bakiyeyi aşmayacak şekilde belirleme
        IF r.Bakiye < 1 THEN
            CONTINUE;  -- bakiye yoksa bu hesabı atla
        END IF;

        v_tutar := TRUNC(DBMS_RANDOM.VALUE(1, r.Bakiye));

        -- İlk 1500 hesap -> mevcut kur ile swift
        IF v_sayac <= 1500 THEN

            Swift_Pkg.SwiftTransfer(
                p_GonderenHesapNo => r.HesapNo,
                p_AliciIBAN       => 'TR' || TRUNC(DBMS_RANDOM.VALUE(1000000000000000, 9999999999999999)),
                p_Tutar           => v_tutar
            );

        -- Son 500 hesap -> random kur güncelle + swift
        ELSE
            v_yeniKur := ROUND(DBMS_RANDOM.VALUE(40, 45), 4);
            Swift_Pkg.KurGuncelle(v_yeniKur);

            Swift_Pkg.SwiftTransfer(
                p_GonderenHesapNo => r.HesapNo,
                p_AliciIBAN       => 'TR' || TRUNC(DBMS_RANDOM.VALUE(1000000000000000, 9999999999999999)),
                p_Tutar           => v_tutar
            );
        END IF;

    END LOOP;

    COMMIT;
END;
/

SELECT * FROM SwiftMesaj;